version: '2.0'
services:
  registry:
    image: registry:2.7
    container_name: docker_registry
    volumes:
      - docker_registry:/var/lib/registry
      - ./registry/config.yml:/etc/docker/registry/config.yml
      - ./registry/htpasswd:/etc/docker/registry/htpasswd
    ports:
      - 5000:5000

  ui:
    image: joxit/docker-registry-ui:latest
    container_name: docker_registry_ui
    environment:
      - REGISTRY_URL=${REGISTRY_URL}
      - REGISTRY_TITLE=${REGISTRY_TITLE:-Registry}
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - SINGLE_REGISTRY=true
      - NGINX_PROXY_PASS_URL=http://registry:5000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 89:80
    depends_on:
      - registry


volumes:
  docker_registry:
  